---
- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh

- name: Clone Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: Install Vim plugins
  command: vim +PluginInstall! +qall

- name: Clone rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv

- name: Clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Install ruby-build
  shell: PREFIX=~/.rbenv ./install.sh
  args:
    chdir: ~/.rbenv/plugins/ruby-build

- name: Make .ssh directory
  file: path=~/.ssh state=directory

- name: Make .zsh directory
  file: path=~/.zsh state=directory

- name: Make .screen directory
  file: path=~/.screen state=directory
