---
- name: Make .ssh directory
  file: path=~/.ssh state=directory

- name: Make .zsh directory
  file: path=~/.zsh state=directory

- name: Make .screen directory
  file: path=~/.screen state=directory

- name: Copy my dotfiles
  copy: src=~/d/projects/github/config/home/{{item}} dest=~/{{item}}

  with_items:
    - .vimrc
    - .gvimrc
    - .zshrc
    - .zsh/oh-my-zsh
    - .ssh/config
    - .irbrc
    - .gitconfig
    - .gitignore
    - .screenrc
    - .screen/leaf
    - .screen/defaults
    - .screen/stem1
    - .screen/stem2
    - .screen/stem3
    - .screen/stem4
