---
- name: Make .ssh directory
  file: path=~/.ssh state=directory

- name: Make .config directory
  file: path=~/.config state=directory

- name: Copy my dotfiles
  copy: src=files/home/{{item}} dest=~/{{item}}

  with_items:
    - .eslintrc
    - .jscsrc
    - .vimrc
    - .gvimrc
    - .tmux.conf
    - .config/fish/config.fish
    - .ssh/config
    - .irbrc
    - .gitconfig
    - .gitignore
    - .tigrc
